### ISSUE TITLE
Faild to load

### ISSUE THREAD

**Issue by richardHaggioGwati** [TylerPottsDev/weather-app-js#1]
Hy man I saw your video on youtub and tried it out but I could not get the API to respond. Your code does not work.

Error from Chrome

Failed to load resource: the server responded with a status of 401 (Unauthorized)
api.openweathermap.org/data/2.5/weather?q=London&units=metric&APPID=afaf9f8d48cff6cafd32e23220bcfdbf:1.

Uncaught (in promise) TypeError: Cannot read property 'country' of undefined
    at displayResults (main.js:24)

**Comment by fled-dev** [comment]
I have this problem too. With his code, it works.

**Comment by nikhil3113** [comment]
Use the arrow function

**Comment by Sirius-G** [comment]
You've got to subscribe to the service and get a free valid authorisation key. Also, instead of the given api base, it is necessary to geo code the location first, so swap the base for this:
http://api.openweathermap.org/geo/1.0/
then you can simply add an extra function to poll weather results using the latitude and longitude generated by the api, like this:

  function getResults (query) {
    fetch(`${api.base}direct?q=${query}&limit=5&appid=${api.key}`)
      .then(geo => { 
        return geo.json(); 
    }).then(getWeather);
  }
  function getWeather (geo) {
    fetch(`https://api.openweathermap.org/data/2.5/weather?lat=${geo[0].lat}&lon=${geo[0].lon}&units=metric&appid=${api.key}`)  
    .then(weather => {
        return weather.json();
        }).then(displayResults);    
  }

Note the getWeather function uses the original api base url, but the parameters have changed. Query had been deprecated and replaced with lat and lon requirements instead.

Best of luck!

**Comment by richardHaggioGwati** [comment]
Thanks for the info

**Comment by Sirius-G** [comment]
You're welcome.
